import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './components/Navigation'
import { AuthProvider } from './Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {



  return (
    <html lang="en" className='bg-slate-200 text-gray-800'>
   
      <body className={inter.className}>
          <AuthProvider>
            <Navigation/>
            {children}
            </AuthProvider>
          </body>
        
    </html>
  )
}
